# Generated by Django 4.2.3 on 2023-07-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="likes_count",
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
