# Generated by Django 4.2.3 on 2023-07-30 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0002_userprofile_likes_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="likes_user_list",
            field=models.ManyToManyField(
                related_name="likes_user_list", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
