# Generated by Django 4.2.3 on 2023-07-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0005_alter_userprofile_likes_user_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="likes_user_list",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="likes_user_list",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
