# Generated by Django 4.2.3 on 2023-08-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0006_remove_userprofile_likes_user_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="factors_array",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
