# Generated by Django 4.2.3 on 2023-08-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0007_userprofile_factors_array"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="age_filter",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city_filter",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country_filter",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
