# Generated by Django 4.2.3 on 2023-08-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0008_userprofile_age_filter_userprofile_city_filter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="age_year",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
