# Generated by Django 4.2.3 on 2023-08-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0009_userprofile_age_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="age_filter",
            field=models.CharField(
                blank=True, default="[18,{age_year}]", max_length=100
            ),
        ),
    ]
