# Generated by Django 4.2.3 on 2023-08-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0010_alter_userprofile_age_filter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="age_filter",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
