# Generated by Django 4.2.3 on 2023-08-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0011_alter_userprofile_age_filter"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="match_user_list",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
