# Generated by Django 4.2.4 on 2023-09-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0012_userprofile_match_user_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='factors_array',
            field=models.TextField(blank=True),
        ),
    ]
