# Generated by Django 4.2.4 on 2023-09-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0013_alter_userprofile_factors_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
