# Generated by Django 4.2.4 on 2023-10-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0014_userprofile_is_profile_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='likes_count',
            field=models.PositiveSmallIntegerField(default=999),
        ),
    ]
